### ISSUE TITLE
Идеи для мода!

### ISSUE THREAD

**Issue by T123216** [Dong-Wo-Long/EnhancementUnits#2]
Пишите сюда только идеи для мода

**Comment by T123216** [comment]
Есть идея можно сделать так чтоб когда юниты берут какой то материал к примеру титан то у них будет увеличится урон но титан будет тратится

**Comment by T123216** [comment]
При выстрели

**Comment by Dong-Wo-Long** [comment]
Сомневаюсь, что это нужно, поэтому закрою за ненадобностью.
