### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by T1232162** [Dong-Wo-Long/EnhancementUnits#3]
Привет поздравляю с новым обновлением оно как всегда  классное но баг с вспышка и не пофиксен если что я с другого ака

**Comment by Dong-Wo-Long** [comment]
Черт знает, что за баг, но я лично ничего не видел и не знаю, все работает.

**Comment by T1232162** [comment]
Вспышки не могут поварачиватся то есть если с боку есть враг то им пофиг.  Если с переди то они стреляют. Нашол формулировки они не крутятся на месте

**Comment by T1232162** [comment]
Тут слова в какую та тарабарщину преврощяются

**Comment by Dong-Wo-Long** [comment]
Понятно. Нет, это не проблема, так и должно быть, вспышки - истребители, двигатель всего один и сзади, нет способа для поворота на одном месте. Посему, больше не беспокой по этой проблеме меня.

**Comment by T1232162** [comment]
Ну ладно
