### ISSUE TITLE
Мне кажется что булавы не до пракаченые  

### ISSUE THREAD

**Issue by T1232162** [Dong-Wo-Long/EnhancementUnits#4]
Они какие-то всё ещё ванильные. Хочется штоп было новое оружие к примеру ряоктивный огнемет стреляет и на месте поподания наносится маленький урон но всё поджигается.

**Comment by Dong-Wo-Long** [comment]
Хватит уже. Не делай то, о чем тебя вообще не просят, я так сделал потому что так хотел, какая к черту разница?
