### ISSUE TITLE
Малинький баг или не доучтёность или всё так и должно быть? 

### ISSUE THREAD

**Issue by T1232162** [Dong-Wo-Long/EnhancementUnits#5]
Извини что беспокою но во время игры я столкнулся с неприятной вещью когда я через процессор командую поли и преказываю стрелять по определённой кординате то они по ней и стреляют но когда рядом стоят повреждёные постройки то саманаводка у пуль переключается на них и стреляет по ним. Что сильно мешает процесору. Извени если это не о очём надобыло побеспокоить.

**Comment by Dong-Wo-Long** [comment]
Издеваешься надо мной что ли? Тогда мне не смешно. Хватит создавать новые "проблемы" из воздуха.

**Comment by T1232162** [comment]
Я не издеваюсь
